export const locales = ["pl", "en", "de", "es", "fr", "it"];

export type TLocale = (typeof locales)[number];

export const DEFAULT_LOCALE = locales[0];

export const PATHS = {
  home: "/",
  "about-us": "/about-us",
  categories: "/categories",
  products: "/products",
  contact: "/contact",
  distributors: "/distributors",
  blog: "/blog",
  policy: "/policy",
  privacy: "/policy",
  rent: "/rent",
  service: "/service",
  support: "/support",
};

/**
 *
 * TODO: Verify all paths below as many of them were auto-generated by AI and need to be checked for accuracy.
 *
 */
export const pathnames = {
  [PATHS.home]: {
    en: "/",
    pl: "/",
    de: "/",
    it: "/",
    fr: "/",
    es: "/",
    // TODO? Language to remove?
    sk: "/",
    cs: "/",
  },
  [PATHS["about-us"]]: {
    en: "/about-us",
    pl: "/o-nas",
    de: "/uber-uns",
    it: "/chi-siamo",
    fr: "/a-propos-de-nous",
    es: "/sobre-nosotros",
    // TODO? Language to remove?
    sk: "/o-nas",
    cs: "/o-nas",
  },

  "/products": {
    en: "/products",
    pl: "/produkty",
    de: "/produkte",
    it: "/prodotti",
    fr: "/produits",
    es: "/productos",
    // TODO? Language to remove?
    sk: "/produkty",
    cs: "/produkty",
  },

  "/products/[...test]": {
    en: "/products/[...test]",
    pl: "/produkty/[...test]",
    de: "/produkte/[...test]",
    it: "/prodotti/[...test]",
    fr: "/produits/[...test]",
    es: "/productos/[...test]",
    // TODO? Language to remove?
    sk: "/produkty/[...test]",
    cs: "/produkty/[...test]",
  },

  "/products/[slug]": {
    en: "/products/[slug]",
    pl: "/produkty/[slug]",
    de: "/produkte/[slug]",
    it: "/prodotti/[slug]",
    fr: "/produits/[slug]",
    es: "/productos/[slug]",
    // TODO? Language to remove?
    sk: "/produkty/[slug]",
    cs: "/produkty/[slug]",
  },

  "/products/[slug]/[subcategory]": {
    en: "/products/[slug]/[subcategory]",
    pl: "/produkty/[slug]/[subcategory]",
    de: "/produkte/[slug]/[subcategory]",
    it: "/prodotti/[slug]/[subcategory]",
    fr: "/produits/[slug]/[subcategory]",
    es: "/productos/[slug]/[subcategory]",
    // TODO? Language to remove?
    sk: "/produkty/[slug]/[subcategory]",
    cs: "/produkty/[slug]/[subcategory]",
  },

  "/products/[slug]/[subcategory]/[product]": {
    en: "/products/[slug]/[subcategory]/[product]",
    pl: "/produkty/[slug]/[subcategory]/[product]",
    de: "/produkte/[slug]/[subcategory]/[product]",
    it: "/prodotti/[slug]/[subcategory]/[product]",
    fr: "/produits/[slug]/[subcategory]/[product]",
    es: "/productos/[slug]/[subcategory]/[product]",
    // TODO? Language to remove?
    sk: "/produkty/[slug]/[subcategory]/[product]",
    cs: "/produkty/[slug]/[subcategory]/[product]",
  },

  [PATHS.contact]: {
    en: "/contact",
    pl: "/kontakt",
    de: "/kontakt",
    it: "/contatti",
    fr: "/contact",
    es: "/contacto",
    // TODO? Language to remove?
    sk: "/kontakt",
    cs: "/kontakt",
  },
  [PATHS.distributors]: {
    en: "/distributors",
    pl: "/dystrybutorzy",
    de: "/vertriebspartner",
    it: "/distributori",
    fr: "/distributeurs",
    es: "/distribuidores",
    // TODO? Language to remove?
    sk: "/distributori",
    cs: "/distributori",
  },
  [PATHS.blog]: {
    en: "/blog",
    pl: "/blog",
    de: "/blog",
    it: "/blog",
    fr: "/blog",
    es: "/blog",
    // TODO? Language to remove?
    sk: "/blog",
    cs: "/blog",
  },

  "/blog/[slug]": {
    en: "/blog/[slug]",
    pl: "/blog/[slug]",
    de: "/blog/[slug]",
    it: "/blog/[slug]",
    fr: "/blog/[slug]",
    es: "/blog/[slug]",
    // TODO? Language to remove?
    sk: "/blog/[slug]",
    cs: "/blog/[slug]",
  },

  [PATHS.policy]: {
    en: "/policy",
    pl: "/polityka-prywatnosci",
    de: "/datenschutz",
    it: "/privacy",
    fr: "/politique-de-confidentialite",
    es: "/politica-de-privacidad",
    // TODO? Language to remove?
    sk: "/zasady-ochrany",
    cs: "/zasady-ochrany",
  },
  [PATHS.privacy]: {
    en: "/policy",
    pl: "/polityka-prywatnosci",
    de: "/datenschutz",
    it: "/privacy",
    fr: "/politique-de-confidentialite",
    es: "/politica-de-privacidad",
    // TODO? Language to remove?
    sk: "/zasady-ochrany",
    cs: "/zasady-ochrany",
  },

  [PATHS.rent]: {
    en: "/rent",
    pl: "/wynajmij",
    de: "/mieten",
    it: "/affitto",
    fr: "/location",
    es: "/alquiler",
    // TODO? Language to remove?
    sk: "/prenajom",
    cs: "/pronajem",
  },
  [PATHS.service]: {
    en: "/service",
    pl: "/serwis",
    de: "/service",
    it: "/assistenza",
    fr: "/service",
    es: "/servicio",
    // TODO? Language to remove?
    sk: "/servis",
    cs: "/servis",
  },
  [PATHS.support]: {
    en: "/support",
    pl: "/wsparcie",
    de: "/unterstutzung",
    it: "/supporto",
    fr: "/soutien",
    es: "/apoyo",
    // TODO? Language to remove?
    sk: "/podpora",
    cs: "/podpora",
  },
};
